engines:
  csslint:
    enabled: false
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.php"
  - "**.module"
  - "**.inc"
exclude_paths:
- source/Salt/**/*
