engines:
  csslint:
    enabled: false
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: false
    # checks:
    #   Generic WhiteSpace DisallowTabIndent TabsUsed NonIndentTabsUsed:
    #     enabled: false
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.php"
  - "**.module"
  - "**.inc"
exclude_paths:
- source/Salt/**/*
