language: php
sudo: required
dist: trusty
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  - LIBSODIUM=true
  - LIBSODIUM=false

addons:
  apt:
    packages:
    - libsodium-dev

before_script:
  - "[[ $LIBSODIUM == true ]] && pecl install libsodium"

script:
  - phpunit --bootstrap source/bootstrap.php source/Threema/MsgApi/Tests

matrix:
  allow_failures:
  - php: nightly
