language: php
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  - LIBSODIUM=true
  - LIBSODIUM=false

before_script:
  - "if [ $LIBSODIUM == true ]; then pecl install libsodium"

script:
  - phpunit --bootstrap source/bootstrap.php source/Threema/MsgApi/Tests

matrix:
  include:
  - addons:
      apt:
        packages:
          - libsodium13
  - addons:
      apt:
        packages:
          - libsodium18
  allow_failures:
  - php: nightly
