language: php
sudo: required
# dist: trusty
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  - LIBSODIUM=stable
  - LIBSODIUM=1.0.10
  - LIBSODIUM=false

before_script:
  - scripts/buildLibsodium.sh
  - scripts/buildLibsodiumPhp.sh

script:
  - scripts/verifyLibsodium.sh
  - phpunit --bootstrap source/bootstrap.php source/Threema/MsgApi/Tests

matrix:
  exclude:
  # HHVM cannot install PECL extensions and is therefore not compatible
  # with libsodium
  - php: hhvm
    env: LIBSODIUM=stable
  - php: hhvm
    env: LIBSODIUM=1.0.10
  allow_failures:
  - php: nightly
