language: php
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  - LIBSODIUM=13
  - LIBSODIUM=false

addons:
  apt:
    packages:
      - libsodium

before_script:
  - "if [ $LIBSODIUM == true ]; then pecl install libsodium"

script:
  - phpunit --bootstrap source/bootstrap.php source/Threema/MsgApi/Tests

matrix:
  allow_failures:
  - php: nightly
