language: php
sudo: required
# dist: trusty
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  - LIBSODIUM=false
  - LIBSODIUM=1.0.0 LIBSODIUMPHP=stable
  - LIBSODIUM=stable LIBSODIUMPHP=stable
  - LIBSODIUM=1.0.10 LIBSODIUMPHP=stable
  - LIBSODIUM=nightly LIBSODIUMPHP=stable
  - LIBSODIUM=stable LIBSODIUMPHP=0.1.3 #(deprecated before namespaces)

before_script:
  - scripts/verifySignature.sh
  - scripts/buildLibsodium.sh
  - scripts/buildLibsodiumPhp.sh

script:
  - scripts/verifyLibsodium.sh
  - phpunit --bootstrap source/bootstrap.php source/Threema/MsgApi/Tests

matrix:
  exclude:
  # HHVM cannot install PECL extensions and is therefore not compatible
  # with libsodium
  - php: hhvm
  include:
  - php: hhvm
    env: LIBSODIUM=false
  allow_failures:
  - php: nightly
