language: php
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  - LIBSODIUM=true
  - LIBSODIUM=false

addons:
  apt:
    packages:
      - libsodium13

before_script:
  - "if [[ $LIBSODIUM != false ]]; then pecl install libsodium; fi"

script:
  - phpunit --bootstrap source/bootstrap.php source/Threema/MsgApi/Tests

matrix:
  allow_failures:
  - php: nightly
