language: php
sudo: required
dist: trusty
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  - LIBSODIUM=stable
  - LIBSODIUM=false

before_script:
  - scripts/buildLibsodium.sh
  - scripts/buildLibsodiumPhp.sh

script:
  - phpunit --bootstrap source/bootstrap.php source/Threema/MsgApi/Tests

matrix:
  allow_failures:
  - php: nightly
